version: '3.4'

services:
  stockchat.api:
    container_name: stockchat_api
    image: stockchatapi
    build:
      context: .
      dockerfile: StockChat.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=StockChat;User Id=sa;Password=OuHiDnGB3A4P8Vj;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "8080:8080"
      - "8081:8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stockchat_sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "OuHiDnGB3A4P8Vj"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: stockchat_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" 

  stockchat.bot:
    container_name: stockchat_bot
    image: stockchatbot
    build:
      context: .
      dockerfile: StockChat.Bot/Dockerfile
    environment:
      - RabbitMq__Uri=rabbitmq://rabbitmq:5672
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__QueueName=stockchat:bot
    depends_on:
      - rabbitmq

  stockchat.frontend:
    container_name: stockchat_frontend
    build:
      context: ../../frontend/stock-chat-client
      dockerfile: Dockerfile
    working_dir: /app
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - stockchat.api